### PR TITLE
TTT: Fixed collision group check

### PR DESCRIPTION
**Pull request by Kefta**
Fixing my fuckups as per usual

### CODE REVIEW

**Comment by robotboy655** [comment]
For fucks sake @Kefta.
```timer.Simple( 1, function() if IsValid( rag ) then rag:CollisionRulesChanged() end )```

Guess what's missing.

**Comment by Kefta** [comment]
Well, I typed a second end on my phone, and when I try to push a second commit on my phone, the push button stays gray. FFS the mobile site is terrible

**Comment by meepdarknessmeep** [comment]
this is great

**Comment by zerfgog** [comment]
code_greatshit

**Pull request closed without merging**
