### PR TITLE
Added util.URLDecode and util.URLEncode

### PR DESCRIPTION
**Pull request by BillyOnWiiUIn144p**
Thought these might be useful for sending data in a URL that includes "URL affecting" characters such as /, ?, &, = etc. that needs escaping or summin

### CODE REVIEW

**Comment by SimonSchick** [comment]
Might be worth implementing something like this too: https://nodejs.org/api/querystring.html#querystring_querystring_parse_str_sep_eq_options

**Comment by thegrb93** [comment]
Spaces should be %20, not + also the carriage return is unnecessary.

**Comment by BillyOnWiiUIn144p** [comment]
%20 and + are used in urlencode and urldecode in PHP.
Removed carriage return

**Comment by willox** [comment]
URLEncode can be done with a single gsub rule by taking the space character out of the first gsub call's pattern and then removing the second gsub call.

**Comment by zerfgog** [comment]
:+1:+1

**Comment by thegrb93** [comment]
I also think this should be in the http library rather than util.

**Comment by zerfgog** [comment]
i disagree

**Comment by Kefta** [comment]
Put it in string, just like JavaScriptSafe, another string formatter for outside purposes.

**Pull request closed without merging**
