### PR TITLE
Replace deprecated function calls with non-deprecated alternatives

### PR DESCRIPTION
**Pull request by markusmarkusz**
This PR contains only some changes.
I only changed some deprecated functions with non-deprecated.
I used the informations which functions are deprecated from here:
http://wiki.garrysmod.com/page/Category:Deprecated_Functions

If you want to merge this, please squash the commits with the function to squash and merge the commits.
I've wasted too much time in trying to squash the commits. (Maybe two or three hours. After I wasted my time, I accidentally deleted the commits by using git rebase -.-)

(And I know that my english isn't really good.)

### CODE REVIEW

**Comment by Kefta** [comment]
The point of using GetConVar is to cache the object to reuse

**Comment by Jvs34** [comment]
All the getconvarstring/int and stuff functions were changed by _Kilburn to be cached internally, this PR is useless as you're even using GetConvar wrong.

**Comment by Kefta** [comment]
@jvs34 they're cached in Lua now iirc, but deprecated either way

**Comment by robotboy655** [comment]
Not to mention you threw in TTT changes too, which you should not have.

**Comment by markusmarkusz** [comment]
Should I create a new PR where I seperate the TTT changes from the others or is this complete PR useless? @robotboy655

**Comment by Kefta** [comment]
Separate base game and TTT changes into different PRs, and cache your GetConVars with local variables.

**Comment by robotboy655** [comment]
As @Jvs34 already pointed out, your GetConvar* replacers will only make the code slower. It makes no sense replace them

**Comment by Kefta** [comment]
@robotboy655 http://wiki.garrysmod.com/page/Global/GetConVarNumber ? Says it's deprecated and to cache GetConVar

**Comment by Bo98** [comment]
That was from before GetConVarNumber had caching inbuilt. The question we have now is: should it still be deprecated or not?

**Comment by Kefta** [comment]
I think so, because caching the convar to a local and running Get* is better than running all of this every time GetConVar* is ran: https://github.com/garrynewman/garrysmod/blob/991cb7a2787a20a73926f2fe3736759a94c8a42e/garrysmod/lua/includes/util.lua#L407-L427

**Comment by markusmarkusz** [comment]
As long as you are discussing about caching ConVars, I will for other deprecated functions (math.Dist and gui.SetMousePos) create a PR, okay?

**Comment by markusmarkusz** [comment]
#1205 and #1206 containing the two other function changes.

**Pull request closed without merging**
