### PR TITLE
TTT: Fix some german translations

### PR DESCRIPTION
**Pull request by markusmarkusz**
Made some changes.
Added a missing translation, fixed some strings, improved some strings, and so on...

### CODE REVIEW

**Comment by MinIsMin** [comment]
Looks good. Translation is good (Some strings depend on the dialect)
Contains some white space fixes but only a few.

According to me it can be merged into master.

**Comment by Kefta** [comment]
Can you remove all of the periods in the ev_ translations? The english counter-part does not have them.

**Comment by markusmarkusz** [comment]
@Kefta 
> Can you remove all of the periods in the ev_ translations? The english counter-part does not have them.

Better?

**Comment by Kefta** [comment]
Yes, thanks

**Pull request merged**
