### PR TITLE
relevel concommand: reloads the map

### PR DESCRIPTION
**Pull request by zerfgog**
credit to @Acecool for the name?

### CODE REVIEW

**Comment by thegrb93** [comment]
Some servers don't want admins to have access to map changing/reloading. No.

**Comment by zerfgog** [comment]
who has access to changelevel?

**Comment by thegrb93** [comment]
The server itself.

**Comment by Acecool** [comment]
I have this in my dev framework, but it's set to superadmin or console; it's meant to be a developer function because there aren't many reasons to reload the same map ( mostly to ensure files load properly after a big change [ load order, new files if there isn't a method to detect new files and load them easily, etc ] but they are human reasons which have use for a shorter console command, and then there are some bad coding examples such as map-vote scripts that reload the current map instead of extending the round system or resetting it [ but these are dynamic so these don't have much use of a shorter command ] ). It's incredibly useful because you don't need to type out changelevel then the full map name ( with the risk of switching to an incorrect map )...

An alternative that might fit better in with the default game structure would be to allow changelevel to be executed without arguments and for that cas to switched to the current map, keeping in mind the current permissions needed for the command.

And to extend on this, it'd be better to rewrite concommand.Run to have its own hook system ( in my framework ) so that changes to argument behavior can easily be added using something along the lines of: concommand.AddArgsHook( "changelevel", function( _p, _cmd, _args ) return ( _p, _cmd, ( !_args || _args[ 1 ] == "" && { game.GetMap( ) } || _args ) end ); but, it should be changed in such a way so that rewriting certain hard-coded commands can actually be changed...

**Comment by thegrb93** [comment]
I also have my own reload map command. I think console command hooking was discussed in the past, but I don't remember how it was concluded. Probably not in favor of it since it wasn't touched since.

**Comment by Acecool** [comment]
Since a lot of us find it useful, it wouldn't hurt to add it into the default game setup... At the least allow empty-argumented changelevel command.

As for command hooking: I'll have to take a look. I haven't been in-tune with a lot lately because of continuing health issues ( reason why I haven't been on facepunch for a long time ) but this caught my eye.

**Comment by willox** [comment]
I have my srcds set to do this on 'retry' server-side which I think is neat. I think it was Hex's idea.

**Comment by thegrb93** [comment]
I like retry much better since its already a commonly used command.

**Pull request closed without merging**
