### PR TITLE
TTT: ConVar for fast switch inventory

### PR DESCRIPTION
**Pull request by Kefta**
http://facepunch.com/showthread.php?t=1450721&p=48447562&viewfull=1#post48447562

Disabled by default to maintain the functionality it has had for three years.

### CODE REVIEW

**Comment by Exho1** [comment]
What was the purpose behind this? Why should the menu be displayed all the time?

**Comment by zerfgog** [comment]
yes

**Comment by Kefta** [comment]
@exho1 So people can see what they're scrolling to

**Comment by Exho1** [comment]
Thats not what I asked Kefta. The menu is nice for people who want to see what they are scrolling to but I don't want to which is why for the past 2 years I've played TTT I have had it disabled. I was asking if those PR adds a convar to disable the menu or not

**Comment by Kefta** [comment]
Yes, by default, this maintains original functionality unless enabled.

**Comment by Exho1** [comment]
Alright. Thank you very much for doign this

**Comment by zerfgog** [comment]
no prob

**Pull request merged**
