### PR TITLE
Made prop_generic default to update on type, like it was before

### PR DESCRIPTION
**Pull request by DaaOtt**

### CODE REVIEW

**Comment by robotboy655** [comment]
*sigh*

**Comment by wiox** [comment]
Doesn't look like there was a default originally anyway.

**Comment by robotboy655** [comment]
@wiox Default being if you do not provide waitforenter in the data table.

**Comment by wiox** [comment]
I still don't see it.

**Comment by DaaOtt** [comment]
@wiox
Before:
`prop:Setup("Generic") --> ERROR`
`prop:Setup("Generic", {}) --> Update on type`
`prop:Setup("Generic", {waitforenter = false} --> Update on type`
`prop:Setup("Generic", {waitforenter = true} --> Update on enter`
First pull:
`prop:Setup("Generic") --> Update on enter`
`prop:Setup("Generic", {}) --> Update on type`
`prop:Setup("Generic", {waitforenter = false} --> Update on type`
`prop:Setup("Generic", {waitforenter = true} --> Update on enter`
Second pull:
`prop:Setup("Generic") --> Update on type`
`prop:Setup("Generic", {}) --> Update on type`
`prop:Setup("Generic", {waitforenter = false} --> Update on type`
`prop:Setup("Generic", {waitforenter = true} --> Update on enter`

**Comment by wiox** [comment]
"Made prop_generic default to update on type, __like it was before__"

Sorry. I was confused by the fact that the title of the PR suggested it was now more similar to the original implementation (which it isn't).

**Pull request merged**
