### PR TITLE
Added more friends/enemies to achievement count

### PR DESCRIPTION
**Pull request by Kefta**
All killable from spawnlist now added

### CODE REVIEW

**Comment by thegrb93** [comment]
No matter how many I kill, I can't get the achievement. Ideas?

**Comment by robotboy655** [comment]
Breen and GMan are hardly friendly though, they are neutral.

**Comment by Kefta** [comment]
I just put them there since they were in the Human + Resistance category.

(GMan is pretty friendly, though. HL wouldn't exist without him)

**Comment by Jvs34** [comment]
I would make Breen an enemy in memory of all the "kill breen" garrysmod.org / workshop spam we had in all these years.

**Comment by Kefta** [comment]
Fine, I'll toss out GMan. Breen is now in enemies

**Pull request merged**
