### PR TITLE
TTT: Change unknown weapon name from "MASSIVE PHASER ARRAY" to "Unkno…

### PR DESCRIPTION
**Pull request by zerfgog**
…wn Weapon Name"
It also falls back on the ClassName thanks to my comrade, code_gs

### CODE REVIEW

**Comment by YourStalker** [comment]
-1 Have a sense of humor u silly goose

**Comment by Kefta** [comment]
+1 You don't know how long this has tortured me for wondering why it did that. I never thought to look

**Comment by zerfgog** [comment]
:+1:+1 I was very confused when I began playing TTT on poorly coded servers

**Comment by aStonedPenguin** [comment]
+1 code said to +1

**Comment by comedinha** [comment]
:-1:
Removed client, the hud bug

**Comment by Kefta** [comment]
What? Can you post a screenshot?

**Comment by comedinha** [comment]
Removed line 6: local client = LocalPlayer()
Line 30: local role = client.GetRole and client:GetRole() or ROLE_INNOCENT

**Comment by Kefta** [comment]
PRing a fix now

**Comment by comedinha** [comment]
I've corrected here, I'm just reporting hehe

**Pull request merged**
