### PR TITLE
TTT: Fixed tabbing

### PR DESCRIPTION
**Pull request by Mr-Gash**
Previously used 3 spaces for indentation. Now properly uses tabs.

### CODE REVIEW

**Comment by Kefta** [comment]
:+1:

**Comment by zerfgog** [comment]
spooky

**Comment by Mr-Gash** [comment]
Yeah I guess. The other two lines are just tabbed out once in this, since I wanted to keep the same amount of lines in all the files changed.

**Comment by robotboy655** [comment]
Pretty sure @svdm already said that he does not want proper tabs in his code.

**Comment by wiox** [comment]
> does not want __proper__ tabs in his code.

ouch

**Comment by Kefta** [comment]
I would love to hear the reason for that

**Comment by svdm** [comment]
Tabs are bad. I'm not really interested in doing a tabs vs spaces debate here, but there are many places where you can find both sides of it outlined in detail.

The TTT codebase has internally consistent indentation (barring a few instances of sloppy pull requests), so there's no tangible benefit to changing it to an arbitrary different style. There's a real downside in that it will ruin the output of ruining various tools (e.g., `git blame`). So, sorry to waste your time, but not going to merge.

**Pull request closed without merging**
