### PR TITLE
Make TTT only precache models once

### PR DESCRIPTION
**Pull request by meepdarknessmeep**
This will help a lot with lag on startup

### CODE REVIEW

**Comment by sirsavary** [comment]
+1, will make TTT much better

**Comment by comedinha** [comment]
:+1:

**Comment by svdm** [comment]
Forcing a precache serverside will also tell all clients to precache (perhaps that's the part causing lag). This is actually necessary, because a client that does not have a traitor weapon cached when a traitor buys one can see the precache happening in their console, hence they know it has been bought. It's been a while but if I recall correctly precaches are shown if you set `developer 1`, which is not flagged as a cheat.

This change will reintroduce that problem for clients that connect after the first round. So for this to work an alternate fix should be found first for the problem above.

**Comment by BlackCetha** [comment]
Maybe you could move the check away from `GAMEMODE.FirstRound` and hook it into the client setup on connection?

**Comment by meepdarknessmeep** [comment]
Alright @svdm, I will look for a more convenient and less laggy method for this.

**Pull request closed without merging**
