### PR TITLE
Added DMenu radio buttons and DMenuOption disable support

### PR DESCRIPTION
**Pull request by KrakenZ**
DMenu:
```lua
DMenu:AddRadioButton( anyGroupId, strText, funcFunction ) -- returns button
DMenu:SetRadioGroupSelected( groupIndex, pnl ) -- Internal
```

DMenuOption:
* Now calls DoClick() on right click without closing the menu (left click unchanged)
```lua
-- Added support for DLabel's
DMenuOption:SetDisabled( bool )
DMenuOption:SetEnabled( bool )

-- Added for radio buttons
DMenuOption:[G/S]etRadioGroup( index ) --> get/set the option's radio group
DMenuOption:UpdateColours( skin ) --> correctly update the colors on state changes
```

Default skin:
* Enabled radio button textures

Example to use the radio buttons:
```lua
local MyButton = vgui.Create( "DButton", Frame )
MyButton:Dock( FILL )

local menu = DermaMenu()
menu:SetDeleteSelf( false )
menu:SetDrawColumn( true )
menu:Hide()

local IconsSizeGroup = "Icons" -- group id can be any type

menu:AddRadioButton( IconsSizeGroup, "Big icons", function() print( "a" ) end ):SetChecked( true )
menu:AddRadioButton( IconsSizeGroup, "Medium Icons", function() print( "b" ) end )
menu:AddRadioButton( IconsSizeGroup, "Small Icons", function() print( "c" ) end )

menu:AddSpacer()

menu:AddOption( "Re-organize icons", function() print( "re-organize" ) end )

MyButton.DoClick = function()
    menu:Open()
end

MyButton.OnRemove = function()
	menu:Remove()
end
```
Result

### CODE REVIEW

**Comment by Exho1** [comment]
I think Radio buttons in general need to be added like checkboxes

**Comment by zerfgog** [comment]
:+1:

**Comment by robotboy655** [comment]
I have a few problems with this PR:
1) I don't see much use of your implementation of radio buttons, there is no way of getting which of the buttons is checked in a group, no data values to determine which button is which, etc.
2) Your right click changes fuck up the hold C context menu right click options for body groups and skins, they will not function properly when right clicked multiple times, the check icon will not update.

**Comment by KrakenZ** [comment]
When I ran my tests, nothing broke. It may be due to an update or just me not properly checking everything. This is a year old PR.

I've made the mistake of doing multiple unrelated changes in one PR, sorry about that :wink:
This should have been made as a separate panel, like Exho1 said.

Anyway, the circle icon doesn't really fit, it's not 16x16 IIRC

**Pull request closed without merging**
