### PR TITLE
fix bug from language strings update

### PR DESCRIPTION
**Pull request by andyault**

### CODE REVIEW

**Comment by Kefta** [comment]
So it's literally that easy to bypass?

**Comment by andyault** [comment]
I wouldn't call it a bypass, this is what language strings are for
the reason it was removed I'd imagine was cause either admins were using language strings to be dumb or people would set language strings in their name and mess something up, something like that

**Comment by Kefta** [comment]
@andyault I thought that was a fixed a LONG time ago

**Comment by andyault** [comment]
it was, but I'm guessing this last update was to fix something left over from that maybe

**Comment by Jvs34** [comment]
Did you test this? language.GetPhrase is clientside while the hook is called serverside, I don't see how this would work.

**Comment by andyault** [comment]
woops, was trying to get zings, didn't even check

**Pull request closed without merging**
