### PR TITLE
Add COLOR:ToInt and IntToColor

### PR DESCRIPTION
**Pull request by Kefta**
It has been a good nine months since I made my original PR to add this( #820 ), but after relearning the entire English language, Lua, and the bit library, I now see what Willox meant. It was an integer the whole time :ok_hand:

### CODE REVIEW

**Comment by thelastpenguin** [comment]
+1 code_gs worked so hard on this

**Comment by wiox** [comment]
I still like the idea of the Color function being able to take a single argument for this rather than a new IntToColor function.

**Comment by Kefta** [comment]
How should Color's tostring act in this case if people want the integer?

**Comment by wiox** [comment]
It's unlikely you'll want the integer for debugging. It's pretty useless compared to each separate channel.

**Comment by Kefta** [comment]
Is it okay if I keep COLOR:ToInt and remove IntToColor in favour of letting Color accept integers?

**Comment by notcake** [comment]
I don't like the function names. It's not clear whether :ToInt packs the alpha channel as well and that IntToColor doesn't handle alpha.
:ToRGB888 and RGB888ToColor (as opposed to ToARGB8888 and RGB8888ToColor) would be ok but feels a bit verbose.

**Comment by Kefta** [comment]
ToRGB888 still feels a bit verbose; ToInt seemed fine since it implied standard RGB implementation that everyone who is aware of color hexes are familiar with

**Comment by thelastpenguin** [comment]
@kefta why not simply include the alpha component and eliminate all ambiguities?

**Comment by Kefta** [comment]
@thelastpenguin The original intent when I made these last year was to use standard #RRGGBB hex/int color implementation that could be used with webpages and storage, however, including the alpha wouldn't be an issue. If everyone agrees ToInt is descriptive enough of a name for an RRGGBBAA color, I'll make the change. I'll also allow Color() to take integers instead of having IntToColor.

**Comment by wiox** [comment]
RRGGBBAA means that Color( 0xFF0000 ) won't be red, which completely invalidates the only good reason this PR exists for.

**Comment by notcake** [comment]
@wiox I think @kefta meant AARRGGBB.

**Comment by Kefta** [comment]
http://pastebin.com/FgXy1fDL This look good? Has support for using integers in Color() and 0xFF0000 is still red

**Comment by wiox** [comment]
```lua
string.len( r ) < 10
```

Wat?

```lua
r < 0xFFFFFF
```

**Comment by Kefta** [comment]
0x000000?

**Comment by wiox** [comment]
You've got to decide if your function takes a string or an integer.

**Comment by Kefta** [comment]
Color had tonumber's before in it, so I'd gladly make it only take integers if you wanted to break that support.

**Comment by Kefta** [comment]
I'll have to take the string since 0x00000000 will cause issues with integer length.

**Comment by Kefta** [comment]
Revised code: http://pastebin.com/Uh4xGVgG

**Comment by Kefta** [comment]
Refer to https://github.com/garrynewman/garrysmod/pull/1050

**Pull request closed without merging**
