### PR TITLE
More gamemode map types

### PR DESCRIPTION
**Pull request by Donkie**
Added missing maptypes for Flood and Jailbreak.

### CODE REVIEW

**Comment by Kefta** [comment]
I thought ba_ was used by something else as well, maybe I'm wrong

**Comment by Donkie** [comment]
Half the maps I use for my servers are prefixed with ba_, I've never seen it being used anywhere else.

**Comment by Kefta** [comment]
Found it: http://css.gamebanana.com/maps/cats/45

Battle arena was a CS:S knifing gamemode that was around for ~5-6 years. Jailbreak was originally a modification of that gamemode. That's why I made the jailbreak filter ba_jail_ since no jailbreak maps I knew at the time had just the prefix ba_

**Comment by Donkie** [comment]
Ah, makes sense.
I believe Battle arena is more of a CSS thing though, compared to Jailbreak which works both in CSS and Garrysmod, thus IMO ba_ should stay.

**Comment by Kefta** [comment]
Yeah, but CS:S maps are widely used in Garry's Mod. I'll bet that most of your JB maps are from CS:S. ba_jail_ should suffice imo

**Comment by Donkie** [comment]
Alright, removed ba_

**Pull request merged**
