### PR TITLE
Added missing translation for weapon menu

### PR DESCRIPTION
**Pull request by markusmarkusz**
Added missing translations for weapon menu (and added some spaces)

### CODE REVIEW

**Comment by Kefta** [comment]
Can you check if it's missing in the other translation files?

**Comment by markusmarkusz** [comment]
Translations for +L.set_fastsw_menu and +L.set_fastswmenu_tip are missing in the other languages too.
In Traditional Chinese missing more translations.

**Comment by Kefta** [comment]
Do you mind giving me a full list of the missing Trad Chinese translations? I can get them all.

**Comment by markusmarkusz** [comment]
Okay. I'm going to make a list with all missing strings for all languages.
Then you and maybe someone other can fill them.

**Comment by Kefta** [comment]
I'm also going to clean up the English file sometime because some of these strings are very grammatically broken and inconsistent.

Portuguese:
"Activa o menu com arma rápido comutador"
"Cuando arma rapido comutador está activado, o menu comutador irá aparecer"

Spanish:
"Activar arma rápida conmutación"
"Si se activa la arma rápida conmutación, el intercambiador de menú aparecerá"

**Comment by markusmarkusz** [comment]
In all languages (except English, German, Portuguese and Spanish (they are in this PR)) the following strings are missing:
- L.set_fastsw_menu
- L.set_fastswmenu_tip

And in Russian and Trad Chinese there is either missing the following strings:
- L.hat_retrieve

I hope that these are all. It may be that I have overlooked some. But I'm not sure.

**Comment by Kefta** [comment]
Thank you; this can be merged. I'll have the rest at a later date when I can contact some IRL people.

**Comment by comedinha** [comment]
Fixed portuguese strings http://pastebin.com/jrpC6h5d

**Comment by markusmarkusz** [comment]
Is this now the complete translation? Then i'll add it to the PR.

**Comment by Kefta** [comment]
@markusmarkusz Although he made some grammatical fixes, the main changes were making the language strings use more South American Portuguese than European, which I guess will have a wider appeal.

**Comment by markusmarkusz** [comment]
@Kefta should I merge it to the branch?

**Comment by comedinha** [comment]
@markusmarkusz Is the Brazilian Portuguese...

**Comment by Kefta** [comment]
@markusmarkusz Yes

**Comment by markusmarkusz** [comment]
I'll add it later/tomorrow.

**Comment by markusmarkusz** [comment]
Merged it.
I merged to the false branch too. :P

**Pull request merged**
