### PR TITLE
Prevent People from buying equipment

### PR DESCRIPTION
**Pull request by GamefreakDE**
Added new hook "TTTCanOrderEquipment" to prevent people from buying equipment.
Open for any suggestions.

### CODE REVIEW

**Comment by markusmarkusz** [comment]
Something like TTTCanOrderEquipment might be better. (Consistence with other hooks like TTTCanIdentifyCorpse, etc.)

**Comment by windowsok** [comment]
Thanks for
  the information your article brings. I see the novelty of your writing, I
  will share it for everyone to read together. I look forward to reading many
  articles from you.
<a
  href="https://wingsio0.com">wingsio</a>

**Comment by Kamshak** [comment]
Can this be fixed to use

``` if hook.Run("TTTCanOrderEquipment", ply, id, is_item) == false then return end ```

That way you could add specific logic and not return anything for items you don't want to handle (so that other addons also get a chance to change the result)

**Comment by sannysc** [comment]
The behavior you described is already supported. If you don't want to deal with the item, then don't return anything, and the hook system will move on to the next listener. It is only when you return something other than ```nil``` does the hook stop.

**Pull request merged**
