### PR TITLE
Update dform.lua

### PR DESCRIPTION
**Pull request by Azarym**
self.m_strConVar is nil.
Cause [ERROR] lua/vgui/dform.lua:132: bad argument #1 to 'RunConsoleCommand' (string expected, got nil)

### CODE REVIEW

**Comment by wiox** [comment]
You don't fix an error by blindly removing code

**Comment by Kefta** [comment]
https://github.com/garrynewman/garrysmod/blob/e7111a4ab8318b69c3a29e2cbea6cc57ec0bcf5a/garrysmod/lua/derma/init.lua#L97

It's not nil; your code is sending in an invalid convar

**Comment by Azarym** [comment]
The problem is when you create the combobox without concommand
Example: DForm:ComboBox("Test")

Its working with other panel because the "OnSelect" isn't overrided by DForm

**Comment by robotboy655** [comment]
You are not really supposed to use that function without a second argument, but oh well, I will fix it.

**Pull request closed without merging**
