### PR TITLE
Fixed being able to noclip while dead

### PR DESCRIPTION
**Pull request by Kefta**
Fixes https://github.com/Facepunch/garrysmod-issues/issues/2408

### CODE REVIEW

**Comment by deinemudda32** [comment]
+1

**Comment by willox** [comment]
Syntax error :+1:

**Comment by Kefta** [comment]
Omfg

**Comment by willox** [comment]
Don't bother fixing it, I'll do it

**Comment by aStonedPenguin** [comment]
Classic code_bs, not testing his pull requests! At least he didn't get broken code into the game for the 4th time.

**Comment by zerfgog** [comment]
Every time. Step it up!

**Pull request merged**
