### PR TITLE
UTF-8 lib and support for UTF-8 data in markup lib

### PR DESCRIPTION
**Pull request by wiox**
This adds a global utf8 library which works similarly to Lua 5.3's utf8 library and uses that in the markup library, allowing for UTF-8 data to be correctly displayed and word-wrapped.

```lua
local obj = markup.Parse( [[
<font=ChatFont>With Spaces:</font>
激光, 這兩個字是甚麼意思

私は日 本人を見つけ ることができ ません

Я не могу найти русский

Hello, World! I am really not artistic.


<font=Chatfont>No Spaces:</font>
激光,這兩個字是甚麼意思

私は日本人を見つけることができません

Янемогунайтирусский

Hello,World!Iamreallynotartistic.

</font>]], 96 )

hook.Add( "HUDPaint", "", function()

	obj:Draw( 100, 100 )

end )
```

Should solve https://github.com/Facepunch/garrysmod-issues/issues/1420.

### CODE REVIEW

**Comment by wiox** [comment]
I should add that this also adds a function not existent in Lua 5.3: utf8.force. It simply replaces any invalid UTF-8 sequence with U+FFFD (the Unicode replacement character).

**Comment by Donkie** [comment]
:+1: x :100:

**Comment by DaaOtt** [comment]
:+1:

**Comment by WinterPhoenix96** [comment]
+1

**Comment by mcd1992** [comment]
:+1:

**Pull request merged**
