### PR TITLE
Pr/2

### PR DESCRIPTION
**Pull request by Jvs34**

### CODE REVIEW

**Comment by Jvs34** [comment]
Wait what fuck

**Comment by SwadicalRag** [comment]
:-1:

**Comment by Acecool** [comment]
Also a ton of whitespace added.. I'd recommend my macro for that:

shortcuts.xml, add after </Macro> ... You can create a new one and name it something and then just overwrite that block
```xml
        <Macro name="ConvertSpaces(5, 4, 3, 2)ToTabs TrimTrailing Save" Ctrl="no" Alt="no" Shift="no" Key="0">
            <Action type="2" message="0" wParam="42024" lParam="0" sParam="" />
            <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1601" wParam="0" lParam="0" sParam="     " />
            <Action type="3" message="1625" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1602" wParam="0" lParam="0" sParam="&#x0009;" />
            <Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
            <Action type="3" message="1701" wParam="0" lParam="1609" sParam="" />
            <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1601" wParam="0" lParam="0" sParam="    " />
            <Action type="3" message="1625" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1602" wParam="0" lParam="0" sParam="&#x0009;" />
            <Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
            <Action type="3" message="1701" wParam="0" lParam="1609" sParam="" />
            <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1601" wParam="0" lParam="0" sParam="   " />
            <Action type="3" message="1625" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1602" wParam="0" lParam="0" sParam="&#x0009;" />
            <Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
            <Action type="3" message="1701" wParam="0" lParam="1609" sParam="" />
            <Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1601" wParam="0" lParam="0" sParam="  " />
            <Action type="3" message="1625" wParam="0" lParam="0" sParam="" />
            <Action type="3" message="1602" wParam="0" lParam="0" sParam="&#x0009;" />
            <Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
            <Action type="3" message="1701" wParam="0" lParam="1609" sParam="" />
            <Action type="2" message="0" wParam="41006" lParam="0" sParam="" />
        </Macro>
```

What this does is replaces spaces to tabs... So 5 spaces, then 4 then 3 then 2. Next, it trims the line so no whitespace is left at the end of any line ( or clears empty lines ). Next, it saves.

You'd be surprised how many KB I shaved off default files by running this through all of them.

Also, take a look at this if you want a different context menu and how to change it ( I changed mine so I can perform the macro right at the top followed by other useful commands )

**Comment by Jvs34** [comment]
The whitespace was a result of the fucked up merge I tried to do which also made this pull request visible here, none of this was supposed to happen anyway.

**Comment by Acecool** [comment]
+1. I'm not great with GIT either.. No worries, I just posted the macro just in case you may also have a use for it ( it is a tremendous help ) but now I remember you and you're more than familiar with all of that anyways.

Willox walked me through squashing ( not sure if you're familiar with that ) but it lets you undo actions in GIT ( The soft one is the one I ended up using I believe ) which led to this result: https://github.com/garrynewman/garrysmod/pull/920 - prior to squashing there were ( well you can count all the squash lines.. ) 26 or so commits and by squashing it undid them and I could submit all changes as 1 ( I did remove some files from that commit though which removed un-used local re-definitions of globals in some of the neighbor files ).

Here are the screenshots: 
https://dl.dropboxusercontent.com/u/26074909/Screenshots/git_squashing/Screenshot%202015-07-11%2016.32.35.png
https://dl.dropboxusercontent.com/u/26074909/Screenshots/git_squashing/Screenshot%202015-07-11%2016.37.32.png
https://dl.dropboxusercontent.com/u/26074909/Screenshots/git_squashing/Screenshot%202015-07-11%2016.32.31.png

**Comment by SwadicalRag** [comment]
(Just to confirm, my :-1: was sarcasm)

:100:+

**Pull request closed without merging**
