### PR TITLE
Fixed PrintTable erroring when it fails tostring

### PR DESCRIPTION
**Pull request by DaaOtt**

### CODE REVIEW

**Comment by wiox** [comment]
tostring shouldn't have any failure conditions

**Comment by wyozi** [comment]
tostringing panels can fail iirc

**Comment by wiox** [comment]
tostring isn't supposed to fail unless given 0 arguments. That should be fixed.

**Comment by robotboy655** [comment]
tostringing physobjects and panels has been already fixed

**Pull request closed without merging**
