### PR TITLE
Include utf8 lib and coroutine extension on menu state init

### PR DESCRIPTION
**Pull request by bmwalters**

### CODE REVIEW

**Comment by uRandomAlex** [comment]
Why? You can do this by yourself if you are making modification to main menu, it'll just increase RAM and CPU usage for other players.

**Comment by robotboy655** [comment]
I don't see any reason for this either.

**Comment by Kefta** [comment]
@urandomalex regardless of this was accepted or not, this doesn't affect RAM or CPU. That's like saying each Lua function you create takes up disk space

**Comment by uRandomAlex** [comment]
@Kefta each Lua function takes up RAM. It's just some bytes, however. Because of laggy HTML menu we need to load as less Lua as we can.

**Comment by Kefta** [comment]
It's absolutely negligible

**Pull request closed without merging**
