### PR TITLE
Add ordering for hooks.

### PR DESCRIPTION
**Pull request by thegrb93**
Not tested enough, but putting here for suggestions and review.

### CODE REVIEW

**Comment by neico** [comment]
I'd rather call it priority, order sounds strange in this context...

I'd probably also add a optional argument for GetTable to get the Priority table as well (or merged, whatever looks better I guess)

I feel this might add some overheat to normal hooks though, so you might want to provide some benchmarks and stress tests and make sure that the priority is only accounted for if there's actually a need for it...

Ideally I'd use the Hooks table and extend it to allow optional fields per hook (which would make adding additional features to the hooks later on easier, or even customizeable behavior, ULX comes to mind) and avoid creating another which basically doubles the memory usage as it's pretty much a copy with added priority numbers.

But I guess that should probably handled by a different PR and have a grace period as there surely are scripts that rely on the current Hook table structure...

**Comment by BillyOnWiiUIn144p** [comment]
Regardless of whether this PR is good or not, this is seriously needed.

**Comment by thegrb93** [comment]
Can't exclude hooks that don't need it because the ones that do need it need to be called before or after the normal ones. If you have a better idea about the structure of the tables without messing up GetTable then let me know.

**Comment by thegrb93** [comment]
New commit, not tested but I uploaded it for feedback. I made normal hooks unaffected so there's no overhead for normal hooks. I'll finish with this idea if it looks good.

**Comment by willox** [comment]
I prefer how ULX does it without any magic numbers. This also seems like a lot of code

**Comment by aStonedPenguin** [comment]
You could modify my implementation of the hook lib here to do this and at the same time even make the hook lib faster by removing the pairs loop.
https://github.com/SuperiorServers/plib_v2/blob/master/lua/plib/libraries/hook.lua

**Comment by thegrb93** [comment]
You can add enums for numbers if you want. It's much more efficient this way since there aren't 2 nested tables.

**Comment by thegrb93** [comment]
And yeah, there's a lot of code because I had to basically write my own ordered sets.

**Comment by thegrb93** [comment]
Should I test and polish this implementation or is there something else you have in mind? I could add an ordered set class with O(log(n)) if needed.

**Comment by thegrb93** [comment]
If it was a skiplist structure, I think insertions and deletions are safe while iterating too.

**Comment by willox** [comment]
If anything is merged at all, it'll have to be 100% compatible with ULX's hook library. There's probably a lot you can simplify with that in mind.

**Comment by thegrb93** [comment]
I'll look at it and make sure of that.

**Comment by thegrb93** [comment]
I'll need to restrict the hook order values to -2, -1, 0, 1, and 2 for that to work. Is there any chance we can get a skiplist class? would make things much cleaner.

**Comment by StidOfficial** [comment]
I need priority order for hook. On my gamemode !

**Pull request closed without merging**
