### PR TITLE
Added check if player is alive when testing players

### PR DESCRIPTION
**Pull request by morfin60**
Added check to ignore ghosts when testing(they could trigger false positive result)

### CODE REVIEW

**Comment by Bo98** [comment]
Doesn't ply:IsActiveTraitor() cover that?

**Comment by svdm** [comment]
Indeed, players are moved to the spectator team as soon as they die, and `IsActiveTraitor` will return false for anyone in that team. Is there a reproducible case where the entity gives a false positive?

**Comment by BlackCetha** [comment]
Because he said "ghosts" ill guess its something with the spec-dm.

**Comment by Kefta** [comment]
Then that's something addon specific and should be handled within the addon

**Comment by morfin60** [comment]
And there is a little problem. Guy i asked to go in tester was not in DM(he was just flying ghost)

**Comment by BlackCetha** [comment]
Give us steps to reproduce the problem so we can see whats going wrong please.
Also, what is a "flying ghost"? Do you mean a dead player in spectator mode?

**Comment by morfin60** [comment]
It was not flying ghost - it was walking ghost with gun in ghost DM which is like in special team

**Pull request merged**
