### PR TITLE
Merged menu.lua and init_menu.lua

### PR DESCRIPTION
**Pull request by Kefta**

### CODE REVIEW

**Comment by wiox** [comment]
This breaks menu_reload.

**Comment by Kefta** [comment]
How does menu_reload work?

**Comment by wiox** [comment]
It sets up the Lua state, includes includes/init_menu.lua, derma/init.lua, includes/vgui_base.lua, skins/default.lua, includes/menu.lua and then calls the MenuStart hook.

**Comment by Kefta** [comment]
Can't this be changed to not call menu.lua anymore? I see no reason to call a file with a single include when another file already calls them all.

**Comment by wiox** [comment]
Does it matter?

**Comment by Kefta** [comment]
Just seems pointless and messy. Guess it doesn't really matter

**Pull request closed without merging**
