### PR TITLE
DFileBrowser Update

### PR DESCRIPTION
**Pull request by TheFreeman193**
### This updates and improves the DFileBrowser VGUI element.
__Changes__
* Now uses _DHorizontalDivider_ allowing tree & list to be resized
* Fix file tree not displaying subdirectories
* Change variable identifiers to match GMod standards
* Now allows wildcard string (_SetSearch_) for refining directory tree
* Current directory view can now be set/got
* Following setup vars can be changed after first load:
 * _SetModels_
 * _SetCurrentFolder_
 * _SetBaseFolder_
 * _SetSearch_
 * _SetPath_
 * _SetName_
 * _SetFileTypes_
* Now uses _DListView_ for displaying normal files, replaces buttons
* _OnSelect_ now reports correct file path instead of base directory
* Base directory node is now accessible (_GetFolderNode_)
* Fixed a significant spelling error in _DHorizontalDivider_.
* Added _SortFiles(desc)_ method
* File header is visible again- list can be sorted
* Now displays current directory in file header
* Now allows multiple file types
* Now enforces accessor function types
* Added _SetOpen_/_GetOpen_ methods
 * Added cookie methods to handle default open/close for base node
* Added overridable method _OnDoubleClick_
* Added overridable method _OnRightClick_
* Added _Clear_ to override method inherited from panel
* Modified background for spawnicons so highlight is visible

Tree/File list width, min and divider width can be handled with _.Divider_ member. This avoids adding lots of accessor funcs unnecessarily:

| Function | Description |
| -------- | ----------- |
| _self.Divider:[Set/Get]LeftWidth(w)_ | Tree width |
| _self.Divider:[Set/Get]LeftMin(w)_ | Minimum tree width |
| _self.Divider:[Set/Get]RightMin(w)_ | Minimum files width |
| _self.Divider:[Set/Get]DividerWidth(w)_ | Divider width |

__To do__
- [x] Iterate through *m_strFilter* to allow multiple file types in filter
- [x] Add vars:
 - [x] Open base node by default
 - [x] Min/max width for tree/file list
 - [x] Width of tree/file list
 - [x] Divider width (?)
- [x] Enforce strings in accessor funcs
- [x] Different action on double click (?)

### CODE REVIEW

**Comment by Kefta** [comment]
I didn't know todo lists existed in markdown before this, that's cool

**Comment by TheFreeman193** [comment]
Yeah, only in GitHub's own brand of markdown though, unfortunately. There's a list of all the extra stuff they've added a little way down [this page](https://guides.github.com/features/mastering-markdown).

**Comment by TheFreeman193** [comment]
__Changes__
* Added _SortFiles(desc)_ method
* File header is visible again- list can be sorted
* Now displays current directory in file header
* Now allows multiple file types
* Now enforces accessor function types
* Added _SetOpen_/_GetOpen_ methods
 * Added cookie methods to handle default open/close for base node
* Added overridable method _OnDoubleClick_
* Added overridable method _OnRightClick_
* Added _Clear_ to override inherited
* Modified background for spawnicons so highlight is visible

Tree/File list width, min and divider width can be handled with _.Divider_ member. This avoids adding lots of accessor funcs unnecessarily:

| Function | Description |
| -------- | ----------- |
| _self.Divider:[Set/Get]LeftWidth(w)_ | Tree width |
| _self.Divider:[Set/Get]LeftMin(w)_ | Minimum tree width |
| _self.Divider:[Set/Get]RightMin(w)_ | Minimum files width |
| _self.Divider:[Set/Get]DividerWidth(w)_ | Divider width |

**Comment by TheFreeman193** [comment]
Preview for changes:
Example 1
Example 2

**Comment by TheFreeman193** [comment]
@robotboy655 Do you think this should reset the file list (on the right) when the base directory is updated or the game path is changed?

**Comment by robotboy655** [comment]
I have no idea what you are talking about.

**Comment by wiox** [comment]
I think it should

**Comment by TheFreeman193** [comment]
At present, if you change the directory from which the tree is generated, the current folder being displayed on the right does not change. This would allow a user to view a directory that doesn't exist on the tree. This isn't a problem since the tree does not follow the current folder, so it's a matter of preference.

**Comment by robotboy655** [comment]
I think it should

**Comment by TheFreeman193** [comment]
Okay then, I'll make the changes and push it later. Cheers

**Comment by TheFreeman193** [comment]
_(Squashed commits)_

**Comment by Kefta** [comment]
How do you squash commits?

**Comment by TheFreeman193** [comment]
The _clean_ way to do it involves resetting the HEAD to match the master, and then staging all the changes in your local repo again. The way I use is only a good idea if noone else has pulled down or forked your repo, as it rewrites history. You run _git rebase -i HEAD~**xx**_ where xx is the number of parent commits you want to mess with. It'll bring up a text file with the number of commits you specified. You can then change the keywords on each line from _pick_ to _squash_ or _fixup_, as well as reorder them. It's risky though, so make sure you check it before you push it. You'll need to run _git push -f_, otherwise GitHub won't let you modify the history.

**Comment by zerfgog** [comment]
:+1:+1

**Pull request merged**
