### PR TITLE
Added ColorRand

### PR DESCRIPTION
**Pull request by Kefta**
Has argument to include a random alpha or not

### CODE REVIEW

**Comment by Bo98** [comment]
math.Rand = real numbers (decimals)
math.random = integers (whole numbers) - exception is if you give no arguments

I'd use math.random here.

**Comment by Kefta** [comment]
Good call

**Comment by robotboy655** [comment]
You'll have to rebase ( sorry ) and add some white space to math.random calls for consistency.

**Comment by Kefta** [comment]
I can't rebase until all my PRs are cleared since I modified my head. I'll remake the PR with the whitespaces

**Pull request closed without merging**
