### PR TITLE
Add math.IsFinite

### PR DESCRIPTION
**Pull request by meepdarknessmeep**
http://facepunch.com/showthread.php?t=1478507

### CODE REVIEW

**Comment by JamesxX** [comment]
While adding these functions as a utility is cool, it doesn't guarantee that they would be used, so we would still see poorly coded addons.

**Comment by wiox** [comment]
Maybe we should just get tonumber patched to work like newer versions of Lua.

**Comment by meepdarknessmeep** [comment]
we could, but that's mostly up to the developers. make a request on garrysmod-requests or garrysmod-issues

**Comment by thegrb93** [comment]
tonumber patch is a very good idea. I can't think of any reason for float exceptions to be parsed.

**Comment by robotboy655** [comment]
tonumber no longer returns nan of inf

**Comment by meepdarknessmeep** [comment]
Nan and inf still exist...

**Pull request closed without merging**
