### PR TITLE
Add TTTSelectRoles Hook

### PR DESCRIPTION
**Pull request by GamefreakDE**
Useful for addons that want to do custom calculations or stuff before the roles are selected.

### CODE REVIEW

**Comment by svdm** [comment]
I don't want addons to influence traitor selection, so you should either remove the `choices` and `prev_roles` tables, or make copies and pass those to the hook.

**Comment by GamefreakDE** [comment]
Is there a bigger reason for this or do you just dislike addons modifying base game mode parts? I wanted to add a new Role and didn't want to override functions too much. I am still happy with the copies, just wondering why you don't like it I'm the first place.

**Comment by markusmarkusz** [comment]
He doesn't
> like that addons get the raw tables

because he doesn't
> want addons to influence traitor selection

**Comment by GamefreakDE** [comment]
I know that its not good to ask you, svdm, here,and maybe you wont even read this, but I realized that my choice to add the hook at this place was a wrong decision, could I make another Pull request to move to hook under line 933? And would I be allowed to take the normal tables then because it doesnt influence traitor selecting anywhere? I made a dumb decision and I dont think that this hook as any use there.

**Comment by svdm** [comment]
What is the goal of the hook exactly? If it was called at the end of SelectRoles, you could pretty much just use TTTBeginRound instead.

**Comment by GamefreakDE** [comment]
I wanted to add new roles to TTT, but now I realize how dumb that was because it's such a hard thing to do and it would require to change nearly the whole gamemode. Tbh I don't think this hook has any use so it can be deleted imo. Sorry, but I didn't though about my idea and just created this pull request without thinking about the result.

**Comment by xxx0365** [comment]
About not wanting addons to influence traitor selection, they already can, so why not have a cleaner way of doing it?

**Comment by monster010** [comment]
@xxx0365 Because a cleaner was is better than a way that is dirty. Good Example: The netcode from source is not so clean, that you notice that when you shoot, you don't always is the player, even if blood splashes.

**Pull request merged**
