### PR TITLE
TTT & Sandbox File Updates and Format Fixes

### PR DESCRIPTION
**Pull request by MrUnknownGamer**
Fixed sandbox files.

### CODE REVIEW

**Comment by bmwalters** [comment]
1. Merge conflicts
2. TTT changes mixed in here
3. Still haven't fixed bugs I addressed in your other PR
4. THIS SHOULD BE DONE BY AN AUTOMATED TOOL SO WE KNOW THAT IT WON'T BREAK EVERYTHING AND WILL ALSO SAVE YOU TIME

**Comment by MrUnknownGamer** [comment]
Still new to how github does all of this

**Comment by robotboy655** [comment]
No. I have already warned the other guy not to do it, I told many times not to do it.

**Comment by MrUnknownGamer** [comment]
Not to do what?  Explain

**Comment by Kefta** [comment]
What errors? You created more errors than fixed -- styling errors are inconsequential and should be done either all at once or in other PRs. Create a PR to remove the unused variables and that's all.

**Pull request closed without merging**
