### PR TITLE
UniqueID2

### PR DESCRIPTION
**Pull request by uRandomAlex**
UniqueID2. Cached, with no collisions possible.

### CODE REVIEW

**Comment by Kefta** [comment]
How is this the "real" UniqueID? Why is another needed?

**Comment by uRandomAlex** [comment]
@Kefta It has no collisions and it's short, so it can be converted to number. All UID1 usage should be replaced with this.

**Comment by Kefta** [comment]
Sorry, I was thinking of AccountID. Use that instead

**Comment by bigdogmat** [comment]
You say we can convert this to a number if we want, but what if the ID part of the steam id is zero? Then it becomes a number only representing the account number. Same could be said for the universe, though that should always be 0 afaik.

If anything you should've implemented this like AccountID because then it's at least useful. Though AccountID is already being added next update.

**Comment by uRandomAlex** [comment]
Sorry, I've not seen AccountID.

**Pull request closed without merging**
