### PR TITLE
string.Comma efficiency

### PR DESCRIPTION
**Pull request by Kefta**
Also added optional second argument for dots instead of commas

### CODE REVIEW

**Comment by wiox** [comment]
This doesn't work for values with decimal points.

**Comment by thegrb93** [comment]
>Don't try to fix what isn't broken?

@wiox It's called improvement. Even though it doesn't work in this case, there are many others that could use it.

**Comment by wiox** [comment]
The second argument is a perfect example of improvement. The unnecessary attempt to make it more efficient which causes bad output for a common use-case isn't.

**Comment by robotboy655** [comment]
I agree with @wiox, an improvement is when there are no regressions.

**Comment by thegrb93** [comment]
Like I said, this isn't a case of improvement, but you shouldn't dismiss attempts of improvement with "don't fix what isn't broken"

**Comment by wiox** [comment]
What happens if optimization PRs begin being accepted and nobody notices the tiny flaws that they introduce?

**Comment by thegrb93** [comment]
That can be said about any pr.

**Comment by wiox** [comment]
Hell no. If this PR had been as simple as allowing for "." rather than "," it'd be obvious if it introduced any bugs or not.

**Comment by thegrb93** [comment]
So what? He wanted to improve the algorithm. Yes a new algorithm requires more testing, but that is okay as long as it is tested.

**Comment by TheFreeman193** [comment]
```lua
local function addCommas( str, period )

	local symbol = period and "." or ","

	str = str:reverse():gsub( "(...)", "%1" .. symbol ):reverse()

	if ( str:StartWith( symbol ) ) then return str:sub( 2 ) else return str end

end

function string.Comma( number, period )

	number = tostring( number )

	local dpos = number:find( "." , 0, true )

	if ( dpos ) then
		return addCommas( number:sub( 1, dpos - 1 ), period ) .. number:sub( dpos )
	else
		return addCommas( number, period )
	end

end
```
Handles decimals and is quicker than both; much quicker with longer strings.

**Comment by Kefta** [comment]
I didn't even think to test floats with this; sorry for the oversight. 

@TheFreeman193 Nice job; please make a PR to my branch for this

**Comment by SimonSchick** [comment]
This kind of commit is why we should have unit tests (for basic functions).

**Comment by zerfgog** [comment]
Please write a unit test lua file for every library function. Please include three different tests per function. Your time starts now.

**Comment by TheFreeman193** [comment]
@Kefta Will do. Going to tweak it a little in order to accommodate negative values, but this won't be an issue.

**Pull request closed without merging**
