### PR TITLE
Make GameDetails run "GameDetails" menu hook

### PR DESCRIPTION
**Pull request by zerfgog**

### CODE REVIEW

**Comment by robotboy655** [comment]
Why?

**Comment by zerfgog** [comment]
Applications I can immediately think of:
- Button on menu to connect to your last joined server
- Tracking server playtimes on menu (most played server, etc)
- UI displaying current server name / w/e
- Other statistics

**Comment by robotboy655** [comment]
None of which are possible for an addon.

**Comment by zerfgog** [comment]
Fair enough. Someone editing the files can add this themself.

**Pull request closed without merging**
