### PR TITLE
Cleaned BBcode tags in addons list #2

### PR DESCRIPTION
**Pull request by EstevanTH**
Hi Rubat and co,

I added some code that removes the very annoying BBcode tags from the descriptions of addons.
This time the code features high performance.

What do you think? Is it good enough this time? :kissing_heart:

### CODE REVIEW

**Comment by robotboy655** [comment]
I already did it @ https://github.com/garrynewman/garrysmod/commit/a0cd0fce6de9fa8d2be0882738a10ae5bcaca9fa

**Comment by EstevanTH** [comment]
Oops...

**Comment by EstevanTH** [comment]
Rubat, where is your tags list? Your code removes non-BB tags: that is so bad. :neutral_face:
I will put a fix to your code so it only removes BB tags. Most non-BB tags are meaningful, for instance `[MR]` for my gaming community and content.

**Comment by robotboy655** [comment]
Maybe that is a good thing, maybe it will stop doing that. Just put full name of the community.

**Pull request closed without merging**
