### PR TITLE
Small Resource Location Fixes

### PR DESCRIPTION
**Pull request by Jake3231**
A few tiny fixes that resolves some issues in the template html files, allowing some resources to be properly referenced.

### CODE REVIEW

**Comment by willox** [comment]
doesn't this just break the menu? the paths are already correct

**Comment by Jake3231** [comment]
`doesn't this just break the menu? the paths are already correct`

In my testing, this doesn't break anything. It just resolves some html errors that the user will never see.

**Comment by willox** [comment]
in my testing it stops the images from loading. i guess it'd fix the images not loading if you try to directly load the templates as html documents, but you're not meant to do that

**Comment by Jake3231** [comment]
Okay.  On macOS this doesn't cause any issues.  It does also resolve any issues that occur when loading these files in a browser.

**Comment by Jake3231** [comment]
It seems as this is no longer necessary.

**Pull request closed without merging**
