### PR TITLE
Fixed some backwards compatibility issues with #1141

### PR DESCRIPTION
**Pull request by Bo98**
Best fix I could think of.

### CODE REVIEW

**Comment by robotboy655** [comment]
Yeah, this is what I currently have, but it has one major downside - what if the skin does not have that variable?

**Comment by Bo98** [comment]
It falls back to the default skin.

https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/derma/derma.lua#L35-L37

**Comment by Bo98** [comment]
Though even if it didn't, the behaviour would be the same as before.

**Comment by robotboy655** [comment]
Was not aware of that fallback stuff, I suppose this fix works then.

**Pull request merged**
