### PR TITLE
Added math.IsBetween and math.IsEven

### PR DESCRIPTION
**Pull request by Mysterypancake1**
I've been in many situations where I needed to check whether a number was between two other numbers, for example when using convars with limits. I just thought this might be helpful, even though a function returning booleans may not be classified as 'math'.

### CODE REVIEW

**Comment by wiox** [comment]
This is math.IsBetweenOrEqual. You can also remove the "== true" from your code.

**Comment by Mysterypancake1** [comment]
Saying 5 isn't in between 5 and 7 for example doesn't sound very logical?

**Comment by wiox** [comment]
Normally I'd agree. In a programming language that has separate "greater than" and "greater than or equal to" operators, I wouldn't. How about math.InRange?

**Comment by TheFreeman193** [comment]
An _inclusive_ parameter might be nice in something like this.

**Comment by bmwalters** [comment]
Not sure how this change is meant to help developers. 
`if math.InRange(5, minheight, maxheight) then`
is actually four more keystrokes than
`if 5 >= minheight and 5 <= maxheight then`
It isn't even hard to remember how to write an "is in range" check, as opposed to other math functions like math.NormalizeAngle (which is also short, but is nice not to have to remember).

It's a similar case with `math.IsEven`. Additionally, the introduction of `math.IsEven` into the codebase might result in people using the following to check if a number is odd:
`if not math.IsEven(num) then` (as opposed to `num % 2 == 1`
*shudder*

Seeing as #1229 (a similar PR) was also closed (:+1:), I don't see this being merged.

**Pull request closed without merging**
