### PR TITLE
Update rope.lua

### PR DESCRIPTION
**Pull request by kulcris**
Add owner to ropes when they are spawned

### CODE REVIEW

**Comment by Kefta** [comment]
Should just cache the GetOwner call instead of calling it five times.

**Comment by kulcris** [comment]
did that throughout entire file,

**Comment by robotboy655** [comment]
Is there any reason to do it? And to do it only on the rope tool?

**Comment by kulcris** [comment]
rope tool is one of the most abused tools in the game, setting the owner will allow someone to create a way to see who created the giant male appendage on the wall without going through miles of logs. 

Should probably be done with the other constraint tools as well though

**Comment by robotboy655** [comment]
You can already do this with cleanup.GetList()[UniqueIDOfaPlayer]["ropeconstraints"]

**Comment by kulcris** [comment]
you cant find who owns specific ropes with that though.

**Comment by robotboy655** [comment]
Sure you can. Here are 5 lines of code that do this exact same thing:
```
for id, ply in pairs( player.GetAll() ) do
	for id, ent in pairs( cleanup.GetList()[ ply:UniqueID() ]["ropeconstraints"] ) do
		ent:SetOwner( ply )
	end
end
```
But it works for all constraints.

**Comment by kulcris** [comment]
ah, awesome. thanks for that didnt realize that is how the table was setup.

**Pull request closed without merging**
