### PR TITLE
TTT: Add C4 Hooks

### PR DESCRIPTION
**Pull request by markusmarkusz**
Here are the C4 Hooks.

### CODE REVIEW

**Comment by Kefta** [comment]
Good DeMorgan's law

**Comment by mcNuggets1** [comment]
Perfeeect.

**Comment by Acecool** [comment]
Actually quite useful but don't forget to create the base functions. If they don't exist the hook won't be called. I'd recommend sticking them in gamemode or GM...

**Comment by markusmarkusz** [comment]
No. They don't have to exist as Gamemode Functions.

**Comment by Kefta** [comment]
@Acecool You're thinking of gamemode.Call

**Comment by Acecool** [comment]
I always had issues; if I didn't make the blank function the hook.Add wouldn't run. I use gamemode for GM extensions ( so my addons will work regardless of whether they're used in gamemodes/ or addons/ because addons/ load prior to GM / GAMEMODE but gamemode exists )...

May have been an old glitch.. I'll double-check it next time I run my dev server.

**Comment by Kefta** [comment]
I mean, you can see it here: https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/modules/hook.lua#L121

**Pull request merged**
