### PR TITLE
Removed random assigning of spawnlist IDs

### PR DESCRIPTION
**Pull request by Kefta**
Because conflicts can occur. This is still a poor solution, overall.

### CODE REVIEW

**Comment by RevoluPowered** [comment]
Whoa, why did that use math.random in the first place?

**Comment by bmwalters** [comment]
@RevoluPowered Garry.

**Comment by RevoluPowered** [comment]
"as the chances of response dwindles, the dev's silently lose interest."

https://imgs.xkcd.com/comics/git_commit.png

**Comment by bmwalters** [comment]
I can't help but laugh at the countless times (in a game with millions of players) where someone might lose one of their categories and be really confused. This really has no reason not to be merged @robotboy655

**Comment by robotboy655** [comment]
I have other ideas for AddPropCategory and how to make it not collide with real spawnlists, ever.

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/4965849af3f70331f050536a11583899dca4227f

**Pull request closed without merging**
