### PR TITLE
Renamed string.StartWith to string.StartsWith

### PR DESCRIPTION
**Pull request by SomeSortOfDuck**
Added string.StartWith as an alias.

### CODE REVIEW

**Comment by Bo98** [comment]
The naming of this function always drove me insane.

**Comment by markusmarkusz** [comment]
What's the meaning behind it?

**Comment by SomeSortOfDuck** [comment]
Consistency with the other function, string.EndsWith, and because it'd
actually be the correct way of saying it.

**Comment by robotboy655** [comment]
No, we no need any more fucking aliases.

**Comment by YuRaNnNzZZ** [comment]
> No, we no need any more fucking aliases.

> Added `string.StartsWith` (alias of `string.StartWith`, for consistency with `string.EndsWith`) (Community Contribution)

😃

**Pull request closed without merging**
