### PR TITLE
Cleaned up weapon variables and functions

### PR DESCRIPTION
**Pull request by Kefta**

### CODE REVIEW

**Comment by robotboy655** [comment]
No. Some of the changes are good, but not all of them. Drop all the white space & ```if SERVER then``` shit and try again if you want.

**Comment by Kefta** [comment]
What if SERVER then shit?

**Comment by Kefta** [comment]
And do you mean whitespace as in the tabs making all the SWEP variables vertically aligned?

**Comment by thegrb93** [comment]
The if SERVER/CLIENT stuff that stops assigning certain variables to the SWEPs. Some of that information might be useful to 3rd party scripts on client/server so they shouldn't be blocked.

**Comment by Kefta** [comment]
http://wiki.garrysmod.com/page/Structures/SWEP

**Pull request closed without merging**
