### PR TITLE
Added unpack functions

### PR DESCRIPTION
**Pull request by Kefta**
For angles, colors, and vectors

### CODE REVIEW

**Comment by notcake** [comment]
Angle:Unpack () and Vector:Unpack () should be implemented in C++ for speed, since the use of .p,.y,.r/.x,.y,.z would call Angle/Vector:__index () 3 times. Also Matrix:Unpack () and corresponding :SetUnpacked (...) functions would be nice.

**Comment by Kefta** [comment]
Yeah, I agree.

**Comment by KateAdams** [comment]
Eh, it depends upon where it's used.  Crossing the C boundary is expensive--like crossing into kernelspace from userspace.  @garrynewman found this out when he implemented the hook system in C++.

**Comment by notcake** [comment]
Ignore this comment if it was already obvious: Angle / Vector:__index() is a Lua -> C call. The Lua implementation of :Unpack() would cause 3 transitions, 1 for each component. The C++ implementation would cause only 1.

**Comment by KateAdams** [comment]
@notcake I wasn't aware vector, angle, and colours overload the `__index` metamethod; if that's the case, then yes, you're correct, it would pass the C boundary 3 times minimum.

**Comment by KateAdams** [comment]
Oh, also, you should set n to 3 in the return value to match the behavior of `table.pack()`:

```lua
print(table.pack(1, 2, 3).n) -- 3
print(table.pack(nil, 3).n)  -- 2
```

**Comment by Kefta** [comment]
@KateAdams Colours don't; they're pure-lua implementation (for some reason)

**Comment by Kefta** [comment]
Going to close this and only make COLOR:Unpack since the rest can be made in C++.

**Pull request closed without merging**
