### PR TITLE
Halloween dynamite

### PR DESCRIPTION
**Pull request by Python1320**
Give comments on whether to include or not.

Yes: Halloween!
No: Prop occasionally turns black when hovered over with context menu.
No: Can't see the dynamite if you don't own TF2.

### CODE REVIEW

**Comment by Kefta** [comment]
Could you do a file.Find check instead so servers could send the model to players?

**Comment by Python1320** [comment]
Halloween has been ruined :ghost:

**Comment by PotcFdk** [comment]
Garry's Mod Halloween 2015, never forget.

**Comment by robotboy655** [comment]
You pretty much gave the reasons why this shouldn't be included. I am mostly worried about the last one.

**Pull request closed without merging**
