### PR TITLE
MouthMoveAnimation performance improvement.

### PR DESCRIPTION
**Pull request by ZehM4tt**
From 0.04 to 0.02 ms

### CODE REVIEW

**Comment by FPtje** [comment]
> 12:55 - ζeh Matt: i got it down from 0.04 to 0.02
12:56 - ζeh Matt: MouthMoveAnimation
12:56 - ζeh Matt: that is if a player is speaking
12:56 - ζeh Matt: if not its literally 0.000001 or osmething
12:56 - ζeh Matt: before it was always at 0.04

He hadn't seen [Jetboom's PR](https://github.com/garrynewman/garrysmod/pull/1191) yet, but this one *should* give a higher performance gain.

**Comment by mcNuggets1** [comment]
Why hadn't this been merged already?

**Comment by Kefta** [comment]
Perhaps ENTITY.GetFlexIndexByName should be implemented in the engine, but otherwise, everything is good

**Comment by bmwalters** [comment]
https://github.com/garrynewman/garrysmod/commit/143b18a0e5afcc1a11dbd210829b9d5f045c54d6

**Comment by Kefta** [comment]
Ew

**Comment by ZehM4tt** [comment]
No longer needed

**Pull request closed without merging**
