### PR TITLE
Clamp the ball size

### PR DESCRIPTION
**Pull request by thegrb93**
So players can't make weird physics with ball duplications with bad ballsize keyvalues.

### CODE REVIEW

**Comment by wiox** [comment]
This sounds like an issue that should be resolved in the duplicator library.

**Comment by thegrb93** [comment]
The dupe files contain keyvalues used by DTVars that get set when the entity pasted. I don't think there's any way to clamp the Keyvalues/DTVar values internally.

**Comment by wiox** [comment]
The issue is that ent:RestoreNetworkVars does not perform the minmax checks. That's a massive flaw and needs resolving.

**Comment by thegrb93** [comment]
Oh okay. That's beyond my knowledge. Should I leave this open or close it and let you guys open an issue on that?

**Comment by thegrb93** [comment]
Oh wait, I just need to make an ENT:RestoreNetworkVars function right?

**Comment by wiox** [comment]
> Should I leave this open or close it and let you guys open an issue on that?

I guess that depends on whether or not people think the edit panel's min/max values should effect duplication.

**Comment by thegrb93** [comment]
>Oh wait, I just need to make an ENT:RestoreNetworkVars function right? I think I can do that.

Nevermind, this function doesn't seem to get called when I duplicate the ball.

**Comment by TheFreeman193** [comment]
@thegrb93 RestoreNetworkVars() is defined when InstallDataTable() is called and hence will override the function you're probably declaring with ``` function ENT:RestoreNetworkVars(dt) ... end ```.

I guess the real problem is that the DTVar system offers no simple means of controlling values when restoring them. One way around this, assuming the restraint is desired, would be to use the OnDuplicated() method to check the DT value.

**Comment by thegrb93** [comment]
I'll change it to that if that's what people want, but I think a clamp is the best way.

**Comment by TheFreeman193** [comment]
Following on from what @wiox said, it'd be nice to have a PreRestoreNetworkVars() hook called [here](../blob/master/garrysmod/lua/includes/extensions/entity.lua#L394) allowing access to the datatable before it is applied. It would permit something like this:
```lua
function ENT:PreRestoreNetworkVars( dt )
	dt.BallSize = math.Clamp( dt.BallSize, 4, 128 )
end
```
Also, if we're not going to be controlling the size, there'd need to be some defensive coding on [this](../blob/master/garrysmod/lua/entities/sent_ball.lua#L141) line to prevent negative pitch values generating out-of-bounds errors.

**Comment by thegrb93** [comment]
Would it possible to just clamp it in the OnBallSizeChanged function?

**Comment by Bo98** [comment]
It is called before the DT var is set so probably not.

**Comment by thegrb93** [comment]
I fixed it properly now. Pls discuss.

**Comment by robotboy655** [comment]
Decided to properly fix it, as well as fix pasting duplicated entities with NetworkVars not calling the NetworkVar proxies/callbacks on first spawn.

This falls into the same category as user input, you must sanitize the values before using them to prevent crazy stuff from happening, the min/max stuff in self:NetworkVar is only for the Editing GUI.

**Comment by robotboy655** [comment]
https://github.com/garrynewman/garrysmod/commit/3e138636eb1b0ad6ed785dedf350020755cff5f1?w=1

**Comment by thegrb93** [comment]
Seems a bit silly to sanitize the variable every time it's used, but I'll roll with it.

**Pull request closed without merging**
