### PR TITLE
Make OnUndo get called by hook.Call

### PR DESCRIPTION
**Pull request by meharryp**
Re-make of #863 since I messed up the pull.

### CODE REVIEW

**Comment by KateAdams** [comment]
Why is it so many people have their branches named "patch-#n", rather than a descriptive branch name (i.e. "onundo-use-hook")?

**Comment by robotboy655** [comment]
I think that is the standard name given when you use this website to submit PRs.

**Comment by wiox** [comment]
We need more imagination. I expect to see more "patch-penis-saggs" in the future.

**Comment by KateAdams** [comment]
So, they're using the website to make changes, and then not testing them?  That's crazy!

**Comment by Bo98** [comment]
Common in GMod repos sadly.

**Comment by TheFreeman193** [comment]
This is now included in a bigger pull for all SendLua GM calls #878

**Comment by meharryp** [comment]
#878 makes this obsolete.

**Pull request closed without merging**
