### PR TITLE
Make light and lamp entities editable

### PR DESCRIPTION
**Pull request by SuperHighVoltage**
This allows the light and lamp entities to be edited from the context menu, allowing for users to change its properties and see the results in real time

### CODE REVIEW

**Comment by robotboy655** [comment]
I wanted to do this for all (most) the entities, but now that I think about it, this would allow people make rainbow lights and shit since you can spam the net messages with Lua.

**Comment by SpencerSharkey** [comment]
Sounds like a really useful addition

+1 for rave lights

**Comment by robotboy655** [comment]
Rave lights are the least of my concerns.

**Comment by robotboy655** [comment]
I have committed a better version of this, including proper support for direct method calls & editable support for more tools.

**Pull request closed without merging**
