### PR TITLE
Changed glock sound from soundscape to path

### PR DESCRIPTION
**Pull request by Kefta**
Stop fucking whining

### CODE REVIEW

**Comment by comedinha** [comment]
This fix the error, but "Weapon_Glock.Single" have a error...

**Comment by Kefta** [comment]
@comedinha The soundscape system really needs to be fixed when it comes to duplicate strings.

**Comment by Violat0r** [comment]
Works but has anyone tried any other HL1 sounds to see if they work?

**Comment by Kefta** [comment]
@Violat0r That's not the problem. It's because most people don't have HL1 mounted and the HL1 version is overwriting the CS:S version for some reason

**Comment by Violat0r** [comment]
Right, I see what you mean. Another possible solution to this would be to rename the soundscape for CS:S/HL1 and in weapon_ttt_glock.lua, something to consider or try.

**Comment by deinemudda32** [comment]
How about fixing this problem the right way instead just for TTT?

**Comment by Kefta** [comment]
@deinemudda32 Rubat already undid the change that supposedly caused this. You want to fix it? Go right ahead

**Comment by deinemudda32** [comment]
But it did work the update before/before.
I didnt want to offend you, if I did. I just don't like such methods.

**Comment by willox** [comment]
Do you guys have a garrysmod/scripts directory? Delete it and let me know if it fixes the issue. Hopefully we'll have this fixed for the next patch.

**Comment by deinemudda32** [comment]
Glock works for me :)

**Comment by willox** [comment]
You'll only have an issue if for some reason an old version of the script is in your garrysmod/scripts directory.

**Comment by Violat0r** [comment]
I have the issue and I do not have garrysmod\scripts. I do have my Garry's Mod installed on my D drive instead of C, not sure if that matters but trying to provide whatever information that may help.

**Comment by robotboy655** [comment]
The problem is with the server, not the client as far as I know.

**Comment by Violat0r** [comment]
I am not sure what I did but it is no longer an issue for me. Perhaps it was something with the hotfix this morning as i did update my client and local server.

**Comment by Violat0r** [comment]
Alright, on my main server that was NOT updated with the hotfix yet, the error exists but I am able to hear the gun fire.

**Comment by Kefta** [comment]
Okay good, we're done here

**Comment by Kefta** [comment]
Thanks for the updates on the issues

**Comment by Violat0r** [comment]
You're welcome. I assume that some of the files may have no been pushed out with the update the other day or something in the hotfix fixed the issue.

**Pull request closed without merging**
