### PR TITLE
TTT: Fix a small issue and remove some unused things

### PR DESCRIPTION
**Pull request by markusmarkusz**
Changes made:
- removed SWEP.LimitedStock because it's no longer buyable.
- removed SWEP:RemovePlayerSample because it's no longer used.
- removed unused if-query.
- removed unused sound.
- added LANG.TryTranslation to safely fix a issue in dna tooltip. Otherwise you can see for example "DNA sample found on pistol_name"

What about making names of the some variables general?
For example rename SWEP.ItemSamples to SWEP.Samples?
These changes aren't really needed so I haven't add them to this PR.
Should these changes be made?

### CODE REVIEW

**Comment by willox** [comment]
> For example rename SWEP.ItemSamples to SWEP.Samples?

You're probably best off trying to never rename anything that could be accessed by third-party scripts. You'd be surprised how often people rely on them.

**Comment by markusmarkusz** [comment]
@willox 
Okay. I knew that this could happen.
This was the reason why I asked this.

**Comment by markusmarkusz** [comment]
Changes made:
- removed unused LANG.GetTranslation
- removed unused LANG.GetParamTranslation
- added local variable for LANG.TryTranslation (Is this useful or not?)

**Comment by svdm** [comment]
Indeed, I've often wanted to rename a bunch of stuff to be more clean and consistent (especially the `GAMEMODE.*` stuff in init.lua) but it will inevitably break a bunch of people's stuff, so it's not worth it.

**Pull request merged**
