### PR TITLE
Added string.HTMLEncode, HTMLDecode, URLEncode and URLDecode

### PR DESCRIPTION
**Pull request by BillyOnWiiUIn144p**
These will be especially useful for web developers using http or HTML panels.

Also changed "in to" -> "into" in some descriptions because they were bugging me

The tables containing HTML entities are taken straight from PHP's htmlentities function.

#1095

### CODE REVIEW

**Comment by Bo98** [comment]
Doesn't work properly without spaces:

```lua
print(string.HTMLDecode("Word&amp;Word"))
```

>Word\&amp;Word

**Comment by meepdarknessmeep** [comment]
This code is fucking disgusting and terrible.

**Comment by xaviergmail** [comment]
Good concept, but implementation leaves a lot to be desired

**Comment by BillyOnWiiUIn144p** [comment]
oh hello you two @aStonedPenguin @meepdarknessmeep

**Comment by notcake** [comment]
```lua
assert(string.HTMLEncode("¡¡") == "&iexcl;&iexcl;")
> assertion failed!

assert(string.HTMLDecode("&amp;quot;") == "&quot;")
> assertion failed!
```

**Comment by BillyOnWiiUIn144p** [comment]
@notcake 

number 1:
Fixed

number 2:
&(?!\S+;) would solve this easily in regex but for Lua patterns this will need some working out (no negative lookahead) :S

**Comment by meepdarknessmeep** [comment]
what about &#XXXX

**Comment by Bo98** [comment]
> Expected behaviour?

No. Decoding should only do a single pass. It's so if anyone actually wants the text `"&quote;` then they can do `&amp;quot;`.

**Comment by BillyOnWiiUIn144p** [comment]
@Bo98

[This](http://billyvenner.xyz/idk.php) is confusing me

```
<?php
	echo(html_entity_decode("&amp;quot;") . "<br>");
	echo(assert(html_entity_decode("&amp;quot;") == "&quot;"));
?>
```

**Comment by Bo98** [comment]
It's because the browser does its own decoding.

**Comment by BillyOnWiiUIn144p** [comment]
Oops. Okay

**Comment by Velkon** [comment]
The face when

**Comment by notcake** [comment]
```lua
string.HTMLDecode("&")
> "&amp;"
string.HTMLDecode("&amp;gt;")
> ">"
```

imsorry

**Comment by BillyOnWiiUIn144p** [comment]
ughhhh

regex pls

**Pull request closed without merging**
