### PR TITLE
Added gm_showmenuerror

### PR DESCRIPTION
**Pull request by Kefta**

### CODE REVIEW

**Comment by robotboy655** [comment]
Sounds like a bad idea. Fix your errors, don't hide them.

**Comment by Kefta** [comment]
It's still enabled by default for normal users, and it still prints in console. Just an option for people who are aware of an error and are trying to test other things.

**Comment by wiox** [comment]
It'd be good if addons couldn't mess with it.

**Comment by Kefta** [comment]
Is there any way to check if a player changed it via console vs. a lua file?

**Comment by wiox** [comment]
I don't think so. Is this tested? Bool isn't a valid method for ConVar objects. You should be using gm_showmenuerror:GetBool() and also move the check in to the OnLuaError hook so that changes to the ConVar take effect immediately.

**Comment by Kefta** [comment]
Oops, bad habit from custom functions. Also, I'll put a check in the hook as well

**Comment by wiox** [comment]
I should note the only reason I'm for this PR is that the error message position sucks for people using the developer ConVar. I'd take some ConVar that repositions it as an alternative too.

**Comment by Kefta** [comment]
I'll make a seperate PR with a convar to move the message to a different corner.

**Comment by Kefta** [comment]
I'll make a seperate PR with a convar to move the message to a different corner.

**Comment by Kefta** [comment]
Damn

**Pull request closed without merging**
