### PR TITLE
Cleaned up weapons

### PR DESCRIPTION
**Pull request by Kefta**
Added SWEP.HoldType to base variables for easy setting without overwriting Initialize, removed useless variables, fixed up a lot of syntax, removed repeat code, and replaced all useless self.Weapon instances with self.

### CODE REVIEW

**Comment by wiox** [comment]
You should remove the instances of 'self.Weapon'.

**Comment by Kefta** [comment]
Hold on, this isn't finished. GitHub decided to push this from the client for some reason

**Comment by Kefta** [comment]
Ignore this; git isn't playing nice

**Comment by Kefta** [comment]
Done @wiox

**Comment by robotboy655** [comment]
I have a few problems with this PR:
1) This is ugly, and completely unnecessary:
```
SWEP.Secondary = 
 {
 	ClipSize = 8,					-- Size of a clip
 	DefaultClip = 32,					-- Default number of bullets in a clip
 	Automatic = false,				-- Automatic/Semi Auto
 	Ammo = "Pistol"
 }
```

2) I really don't like the idea of adding SWEP.HoldType by default, it will just add confusion, especially for new comers when they start overriding SWEP:Initialize and complain why SWEP.HoldType does not work.

3) And I really hate the fact that you changed some SWEP.* fields into locals. There's absolutely no need for that, you are just fucking up "modding" support of those SWEPs.
```
 SWEP.HealAmount				= 20	-- Maximum heal amount per use
 SWEP.MaxAmmo				= 100	-- Maxumum ammo
```

```
local HealAmount	= 20	-- Maximum heal amount per use
```

**Comment by Kefta** [comment]
I agree with 3; I made it a while ago and don't remember why I made them locals. As for 1, I can agree to the preference and I will change it. On 2, I assume that's what was intended since your NP++ highlighting plugin considers SWEP.HoldType as a default variable, plus I think it's just more convenient. People can always just run SetHoldType themselves if they're starting on SWEPs, and I think it's just useful overall.

**Comment by robotboy655** [comment]
If you wish to get this in, recreate it with fixes for stuff I pointed out, and move the TTT stuff into a separate PR.

**Pull request closed without merging**
