### PR TITLE
TTT: Fixed console chat behaviour

### PR DESCRIPTION
**Pull request by Kefta**
Last one hopefully :rainbow:

### CODE REVIEW

**Comment by wiox** [comment]
This entire file is actually calling base methods wrong, I'm surprised it works. Even if not using DEFINE_BASECLASS and a BaseClass upvalue, the self parameter to each method should be the gamemode itself.

**Comment by Kefta** [comment]
So should I be calling baseclass.Get/DEFINTE_BASECLASS or replace the self calls with GAMEMODE?

**Comment by wiox** [comment]
It doesn't matter that much, but only because of pure luck.

```lua
self.BaseClass:Method() -- Wrong, self parameter passed to Method is not an instance of the gamemode
self.BaseClass.Method( self ) -- Wrong if the gamemode is ever derived from, but I don't know anybody that does this with TTT.
baseclass.Get( "gamemode_base" ) . Method( self ) -- Right
```

Instead of baseclass.Get you'd ideally use the DEFINE_BASECLASS macro.

**Comment by Kefta** [comment]
@wiox @svdm Baseclass fixed. I'll fix it in the other TTT files in a separate PR

**Comment by wiox** [comment]
You need to pass the gamemode's instance as the first parameter, not the base class itself.

    BaseClass.Method( self, ... )

**Comment by Kefta** [comment]
@wiox Thanks; never called the baseclass this way before

**Pull request merged**
