### PR TITLE
Bots will respawn without needing to attack

### PR DESCRIPTION
**Pull request by wiox**
Good for development (or just shooting bots).

### CODE REVIEW

**Comment by Exho1** [comment]
Oh yes, I've wondered why bots wont respawn when I kill them

**Comment by Exho1** [comment]
Oh yes, I've wondered why bots wont respawn when I kill them

**Comment by Exho1** [comment]
Oh yes, I've wondered why bots wont respawn when I kill them

**Comment by wiox** [comment]
Calm down bro

**Comment by Nyaaaa** [comment]
This is a nice feature to have!

**Comment by Exho1** [comment]
Well that should not have posted 3 times

**Pull request merged**
