### PR TITLE
math.Approach Optimization

### PR DESCRIPTION
**Pull request by thegrb93**
Slight optimization to this function which is called very frequently. I recorded 25% speed increase. If the math functions were made local then it would be a 40% speed increase.

### CODE REVIEW

**Comment by meepdarknessmeep** [comment]
this isn't even an optimization - it completely changes how it works

**Comment by thegrb93** [comment]
No it doesn't. Explain what makes you think that.

**Comment by thegrb93** [comment]
You and robotboy need to practice your math skills.

**Comment by Kefta** [comment]
It does. For example, math.Approach( 100, 101, -50 ). Before, that would return 100, but now it returns 50. I know it's a bit illogical to use math.Approach that way in the first place, but it was a behaviour that your change affects.

**Comment by Bo98** [comment]
https://github.com/garrynewman/garrysmod/blob/c4deb9d9ebf89eac19044b508b5775ff8ffb4be4/garrysmod/lua/includes/extensions/math.lua#L210

**Comment by Kefta** [comment]
Oh, damn. @thegrb93 is right

**Comment by robotboy655** [comment]
It's not about math skills, its about the one line GitHub chose to omit.

**Pull request merged**
