### PR TITLE
Fixed table.IsSequential being inaccurate in some cases

### PR DESCRIPTION
**Pull request by Bo98**
As discussed in great detail in the Next Update thread.

### CODE REVIEW

**Comment by robotboy655** [comment]
Why change ```i``` and the position of the ```if```? It serves no benefit or makes no difference?

**Comment by Kefta** [comment]
What's the big deal if it makes no difference?

**Comment by thegrb93** [comment]
It actually does make a difference by increasing number of ops. I don't like it either.

**Comment by Bo98** [comment]
I just copy and pasted what we decided. I can easily switch the order you want.

**Comment by Bo98** [comment]
Done.

**Pull request merged**
