### PR TITLE
Fixed main menu text shadow transparency on OS X

### PR DESCRIPTION
**Pull request by Bo98**
Somewhat addresses Facepunch/garrysmod-issues#90. This could be happening to other websites loaded through a HTML/DHTML control but it won't affect most and it is fixed for the main menu.

### CODE REVIEW

**Comment by KateAdams** [comment]
What's with the different newlines?

**Comment by Bo98** [comment]
There were a few trailing ones which were trimmed.

**Comment by robotboy655** [comment]
Before/After pic? I have tried that on Windows and couldn't see any noticeable differences.

**Comment by Bo98** [comment]
Note the text shadow

Before:
Before

After:
After

Never was a bug on Windows but was one on OS X.

**Pull request merged**
