### PR TITLE
Fix game not closing competely

### PR DESCRIPTION
**Pull request by MrUnknownGamer**
Pretty sure this fixes problem where game takes 4 seconds to close but is still open. You would have to go into task manager and quit hl2.exe

Hopefully fixes problem

### CODE REVIEW

**Comment by zerfgog** [comment]
>Pretty sure this fixes problem
Probably want to make sure this actually fixes it

**Comment by thegrb93** [comment]
I turned off windows problem reporting and it doesn't stay open for me anymore.

**Comment by MrUnknownGamer** [comment]
> Probably want to make sure this actually fixes it first

Works fine for me. I don't know if it will work for others is what I'm saying.

**Comment by BillyVenner** [comment]
@thegrb93

Does that mean there's an error happening every time Garry's Mod closes?

**Comment by zerfgog** [comment]
Maybe because `RunGameUICommand` doesn't exist anymore?

**Comment by thegrb93** [comment]
It only happens after joining a server. It doesn't happen with singleplayer. And yeah, there's an error when it happens. This is all windows problem reporting says:
```
Faulting application name: hl2.exe, version: 0.0.0.0, time stamp: 0x57164c47
Faulting module name: client.dll, version: 1.0.0.1, time stamp: 0x571c3a2b
Exception code: 0xc0000005
Fault offset: 0x000ef44a
Faulting process id: 0x521c
Faulting application start time: 0x01d1be90d5ae6e19
Faulting application path: C:\Steam\steamapps\common\GarrysMod\hl2.exe
Faulting module path: c:\steam\steamapps\common\garrysmod\garrysmod\bin\client.dll
Report Id: 4cd466fc-36b8-420c-96b6-b79899168719
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by robotboy655** [comment]
@thegrb93 Can you see if that issue persists on Dev?

**Comment by thegrb93** [comment]
I can't switch my server to dev since its remotely hosted and I don't think a vanilla multiplayer gmod server on dev is confirmation enough. I'll turn error reporting back on after the next update and see what happens.

**Comment by willox** [comment]
You'll probably find it's caused by ropes. Should be fixed in the dev branch (either way, this PR is certainly not the fix.)

**Pull request closed without merging**
