### PR TITLE
few non atomic changes, see description.

### PR DESCRIPTION
**Pull request by SimonSchick**
Revamped dragging/sizing system to work on all borders and corners
Removed empty function descriptors
Changed a few internal variables(m_ syntax is retarded)
Added SetBorderThreshold(number) to set the size of the sizing area
Added SetMaxWidth/Height(num) which limits the panels size
Minor optimisations

### CODE REVIEW

**Comment by willox** [comment]
Changing the names of the member variables could potentially break some scripts and the drag code is pretty hard to read.

**Comment by SimonSchick** [comment]
The whole point of accessors is that people don't use the member variables.
If they access internal things it's their own fault if it breaks.

And regarding the "hard to read part", how would you suggest to make it more readable?

**Comment by willox** [comment]
There's no point making changes that'll break something just because the changes can be made. Try to keep compatibility.

The hard to read part is mostly just the pyramids in PANEL:Think. Space it out a bit and it'll probably be fine. I was playing with DFrames the other day and agree that being able to resize them from every side would be pretty cool.

**Comment by SimonSchick** [comment]
I can't be arsed to install gmod and edit the PR.

If you want the functionalities, merge it and edit the bits you don't like.

**Pull request closed without merging**
