### PR TITLE
Added hook OnPropertiesMenuOpened

### PR DESCRIPTION
**Pull request by BillyOnWiiUIn144p**
This hook will allow for addons to create more advanced properties menus.

At the moment, we can only use properties.Add to add to the properties list and the functionality of it is quite limited.

If we add this hook, it will allow for addons to programmatically change this DermaMenu by being able to add sections and use the DermaMenu functions. This allows for trees of sections (SubMenus), spacer usage (AddSpacer) and more.

The alternative to this is to add more advanced functions to the properties library. In my scenario, I would like to add a small section on the properties list for my latest addon which I would like to have SubMenus and the like.

This cannot be solved by detouring OpenEntityMenu as you would need to access the DermaMenu which is local.

### CODE REVIEW

**Comment by robotboy655** [comment]
But you can already do both?
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/autorun/properties/bodygroups.lua#L33-L88

https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/autorun/properties/editentity.lua#L7

https://github.com/BillyOnWiiUIn144p/garrysmod/blob/patch-1/garrysmod/lua/includes/modules/properties.lua#L85
https://github.com/BillyOnWiiUIn144p/garrysmod/blob/patch-1/garrysmod/lua/includes/modules/properties.lua#L66-L68

**Comment by BillyOnWiiUIn144p** [comment]
I should learn how to read

Thanks

**Comment by BillyOnWiiUIn144p** [comment]
Actually MenuOpen isn't not documented on [the wiki](http://wiki.garrysmod.com/page/properties/Add)

**Comment by robotboy655** [comment]
Added a few missing things

**Pull request closed without merging**
