### PR TITLE
Fixed DHTMLControls

### PR DESCRIPTION
**Pull request by Bo98**
After the Awesomium functions and hooks now work/exist, this control can now be fixed. It was pretty much broken at everything except entering URLs into it.

Side notes about the reasoning behind some of the changes:
* `self.Refreshing` was replaced with a URL check as such check was required to prevent a double history insertion on setup. If the controls were hooked before the initial page began loading (likely scenario as `:OpenURL(...)` doesn't start loading immediately) then the history would be appended on setup and again on load. Instead of removing the initial insertion, a history check was added in case someone decided to add the controls later. This also covers refreshes so that special boolean isn't required now.
* `self.NavStack` was useless and is now removed.

### CODE REVIEW

**Comment by zerfgog** [comment]
A+ commit :+1:+10

**Comment by Bo98** [comment]
Works fine for me. In what case is it glitchy for you?

**Comment by zerfgog** [comment]
1. Navigate to http://wiki.garrysmod.com
2. Click on the "Getting Started" link on the home page
3. Click on the "Main Menu" link from the "Getting Started" page
4. Hit the back arrow until you cannot go back any farther
5. Hit the forward arrow once
All forward history should be gone now.

**Comment by zerfgog** [comment]
Alright, so there aren't as many bugs as I'd thought.
Some flaws though:
- Refreshing shouldn't add a new history entry
- When you refresh, instead of disabling the button, replace it with the "cancel loading" button as most browsers do. Then this button can be remoevd from the right side.

**Comment by Bo98** [comment]
> * Refreshing shouldn't add a new history entry

Doesn't happen for me.

> * When you refresh, instead of disabling the button, replace it with the "cancel loading" button as most browsers do. Then this button can be remoevd from the right side.

I didn't touch this but I agree that it's retarded so I'll add a commit for that.

**Comment by Bo98** [comment]
There is a history corruption issue with fragment identifiers but it is impossible to fix currently without constantly (eg. Think hook/timer) checking the URL property.

@willox Can we get `Awesomium::WebViewListener::View::OnChangeAddressBar`? Not sure whether CEF is anywhere near ready or not.

**Comment by Bo98** [comment]
> * When you refresh, instead of disabling the button, replace it with the "cancel loading" button as most browsers do. Then this button can be remoevd from the right side.

Added now.

**Comment by zerfgog** [comment]
This will need to be updated for http://wiki.garrysmod.com/page/Panel/StopLoading for the next update.

**Comment by Bo98** [comment]
Done.

**Comment by Bo98** [comment]
@zerfgog The merging of the stop and refresh buttons unfortunately won't happen (and thus is reverted) since apparently some addons relied on the internal view hierarchy of DHTMLControls and broke when the buttons were merged.

**Comment by zerfgog** [comment]
@Bo98 :neutral:

**Comment by Kefta** [comment]
Put a warning out next update, deprecate the behaviour, merge your PR

**Comment by Bo98** [comment]
This control is eventually going to be deprecated and replaced in its entirety when CEF is implemented so we can wait until then.

**Pull request merged**
