### PR TITLE
Added table.IsEmpty()

### PR DESCRIPTION
**Pull request by yupi2**
Checks if there is a key/value in a table.

### CODE REVIEW

**Comment by Kefta** [comment]
Uh, #tbl == 0?

**Comment by robotboy655** [comment]
@Kefta, that is not a reliable way of doing it ( it doesn't count string indices, etc ).

But we do not need more pointless aliases.

**Comment by yupi2** [comment]
@Kefta That only works correctly for sequential tables (tables indexed 1 through X with all numbers in between).

@robotboy655 It would be better to just add 5 lines to a file than to have people duplicate it in their addons multiple times or have people incorrectly assuming things like @Kefta

**Comment by thegrb93** [comment]
next(tbl)==nil

**Comment by yupi2** [comment]
@thegrb93 What's the point in typing out `type(s) == "string"` when you have `isstring(s)`?
In the case of `table.IsEmpty(tbl)`, it's much more obvious what is happening compared to `next(tbl) == nil`.

**Comment by thegrb93** [comment]
I prefer using the functions I know rather than having to remember a huge list of small utility functions.

**Pull request closed without merging**
